import type { Metadata } from "next";
import { Bowlby_One_SC, DM_Mono } from "next/font/google";
import "./globals.css";

const bowlbyOneSC = Bowlby_One_SC({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--font-bowlby-one-sc",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-dm-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bowlbyOneSC.variable} ${dmMono.variable} antialiased font-mono font-medium text-zinc-800`}
      >
        {children}
      </body>
    </html>
  );
}
